on:
  push:
    branches: main
  pull_request:
    branches: main

name: R-CMD-check-special

jobs:
  sanitizers-and-valgrind:
    runs-on: ubuntu-latest
    name: ${{ matrix.config.name }}
    container:
      image: ghcr.io/r-hub/containers/${{ matrix.config.name }}:latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: "clang-asan" }
          - { name: "clang-ubsan" }
          - { name: "gcc-asan" }
          - { name: "valgrind" }
          - { name: "rchk" }
          - { name: "gcc16" }
          - { name: "clang22" }
          - { name: "rhel9" }

    env:
      MAKEFLAGS: -j4
    steps:
      - uses: r-hub/actions/register-redhat@main
        if: matrix.config.name == 'rhel9'
        env:
          REDHAT_ORG: ${{ secrets.REDHAT_ORG }}
          REDHAT_KEY: ${{ secrets.REDHAT_KEY }}

      - name: install git & qpdf for rhel9
        if: matrix.config.name == 'rhel9'
        run: |
          subscription-manager repos --enable codeready-builder-for-rhel-9-$(arch)-rpms
          dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm -y
          yum --enablerepo=epel install -y git qpdf

      - uses: r-hub/actions/checkout@main
        with:
          submodules: true
      - uses: r-hub/actions/platform-info@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          job-config: ${{ toJson(matrix.config) }}
      - uses: r-hub/actions/setup-deps@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          job-config: ${{ toJson(matrix.config) }}
      - uses: r-hub/actions/run-check@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          job-config: ${{ toJson(matrix.config) }}
